### ISSUE TITLE
Events Pages need better markup and corrected Schema/hAtom

### ISSUE THREAD

**Issue by andrebu** [iamandrebulatov/Theme-Redesign-and-SEO-Overhaul#30]
Basic obstacle where the markup is a pain to reach and may be overwritten on update.

**Comment by andrebu** [comment]
According to "The Events Calendar" documentation, It may be possible to customize the template files for this plugin such that the customizations are not overwritten on plugin update: 
- https://theeventscalendar.com/knowledgebase/themers-guide/?utm_medium=plugin-tec&utm_source=generaltab&utm_campaign=in-app

**Comment by montreyw** [comment]
Perfect!

**Comment by andrebu** [comment]
[Overhaul is complete](https://github.com/iamandrebulatov/Theme-Redesign-and-SEO-Overhaul/commit/4ac2ff1f1b099902267099b77f44fd216506565e) for both hAtom (removed hEntry and added h-event markup) and Schema.org markup.

Tests can confirm here:
- [test http://earmilk.com/events/?=](https://developers.google.com/structured-data/testing-tool?url=http%253A%252F%252Fearmilk.com%252Fevents%252F%253F%253D)
- [test http://earmilk.com/event/ultra-music-festival-miami-2016/](https://developers.google.com/structured-data/testing-tool?url=http%253A%252F%252Fearmilk.com%252Fevent%252Fultra-music-festival-miami-2016%252F%253F%253D)
- [test http://earmilk.com/event/ultra-music-festival-miami-2016/?=](https://developers.google.com/structured-data/testing-tool?url=http%253A%252F%252Fearmilk.com%252Fevent%252Fultra-music-festival-miami-2016%252F%253F%253D)

---

Both the **Events Archive Page** at `/events` as well as **Single Event Pages** are now both almost perfectly compliant with both hAtom and Schema structured data markup standards.

<img width="1280" alt="screen shot 2016-02-13 at 3 15 59 am" src="https://cloud.githubusercontent.com/assets/3777877/13026772/1187d328-d202-11e5-928e-54388eab7c24.png">
<img width="1280" alt="screen shot 2016-02-13 at 3 16 07 am" src="https://cloud.githubusercontent.com/assets/3777877/13026774/1188de80-d202-11e5-818e-08654ce3bf7a.png">
<img width="1280" alt="screen shot 2016-02-13 at 3 16 10 am" src="https://cloud.githubusercontent.com/assets/3777877/13026776/118a0d6e-d202-11e5-8381-8b25c8fddbe6.png">
<img width="1280" alt="screen shot 2016-02-13 at 3 16 18 am" src="https://cloud.githubusercontent.com/assets/3777877/13026775/1189442e-d202-11e5-9294-404e4b1ebb29.png">
<img width="1280" alt="screen shot 2016-02-13 at 3 16 28 am" src="https://cloud.githubusercontent.com/assets/3777877/13026773/1188b7d4-d202-11e5-9dfd-f6bad272b2f3.png">

---

Several errors remain on the Events Archive page as several Event Posts are simply missing location data, while others have the price set as a range rather than as a fixed value.  Both simply must be entered and properly in order for these 14 pictured errors to be eliminated.
<img width="1280" alt="screen shot 2016-02-13 at 3 31 49 am" src="https://cloud.githubusercontent.com/assets/3777877/13026790/5c9611fe-d202-11e5-8b0b-592b3344a247.png">
<img width="1280" alt="screen shot 2016-02-13 at 3 31 53 am" src="https://cloud.githubusercontent.com/assets/3777877/13026789/5c95b1b4-d202-11e5-93c2-74f31925d50f.png">
<img width="1280" alt="screen shot 2016-02-13 at 3 31 56 am" src="https://cloud.githubusercontent.com/assets/3777877/13026788/5c950b24-d202-11e5-9ed3-e08a153a2e37.png">

**Comment by andrebu** [comment]
A [custom PHP template file](https://github.com/iamandrebulatov/Theme-Redesign-and-SEO-Overhaul/commit/25f2a8923245ebdbc4362300f7e790b41a723753) is being used for the EVENTS Archive page.

If this customization is desired, the custom archive PHP template usage must be enabled in 
`WP Left Admin Nav Panel > Events > Settings > Display > Basic Template Settings > Event Template`:

<img width="1055" alt="screen shot 2016-02-13 at 3 40 01 am" src="https://cloud.githubusercontent.com/assets/3777877/13026818/c53d2ba6-d203-11e5-8f95-b416350a8d3d.png">

<img width="1280" alt="screen shot 2016-02-13 at 3 39 58 am" src="https://cloud.githubusercontent.com/assets/3777877/13026820/c7856f22-d203-11e5-9ba1-8b042ef60b27.png">
