### ISSUE TITLE
Author Image Schema social plugin avatar issue

### ISSUE THREAD

**Issue by andrebu** [iamandrebulatov/Theme-Redesign-and-SEO-Overhaul#33]
Need a solution to insert 'itemprop="image"' into facebook social image avatar plugin plugin plugin.

**Comment by iamandrebulatov** [comment]
Yet another garbage plugin to blame.

Error:
`Fatal error: Call to undefined function has_wp_user_avatar() in /home/www-data/earmilk/public/wp-content/themes/mag-wp/index.php on line 51`

**Comment by iamandrebulatov** [comment]
Plugin completely out of date.

Version 1.5 instead of 2.0.6 - even more time wasted on trash.

`has_wp_user_avatar` not at all present in plugin's functions file.

<img width="1280" alt="screen shot 2016-02-15 at 12 27 56 am" src="https://cloud.githubusercontent.com/assets/3777877/13040517/11188552-d37b-11e5-990f-6457004ad17b.png">

**Comment by andrebu** [comment]
`index.php` was like this:
`echo get_avatar( get_the_author_meta( 'user_email' ), 300 );`

Is now like this:

```
<?php 
    $wp_avatar_profile    = get_user_meta( $user_id, 'wp_avatar_profile', true );
    $wp_fb_profile        = get_user_meta( $user_id, 'wp_fb_profile', true );
    $wp_avatar_capability = get_option( 'wp_avatar_capability', 'read' );
    $size = '300';
    $atts = array( 'extra_attr' => 'itemprop="image"' );
    if ( user_can( $user_id, $wp_avatar_capability ) ) {
        if ( 'wp-facebook' == $wp_avatar_profile && ! empty( $wp_fb_profile ) ) {
            $fb = 'https://graph.facebook.com/' . $wp_fb_profile . '/picture?width='. $size . '&height=' . $size;
            echo "<img alt='facebook-profile-picture' src='{$fb}' height='{$size}' width='{$size}' itemprop='image' />";
        } else {
            echo get_avatar( get_the_author_meta( 'user_email' ), 300, '', '', $atts );
        }
    } else {
        echo get_avatar( get_the_author_meta( 'user_email' ), 300, '', '', $atts );
    }
?>
```
