### ISSUE TITLE
Facebook comment fails to be pulled into aggregate count

### ISSUE THREAD

**Issue by andrebu** [iamandrebulatov/Theme-Redesign-and-SEO-Overhaul#34]
Function:

``` php
function comments_evolved_get_facebook_count($url = "") {
  if(empty($url)){ $url = get_permalink(); }
  $link = 'https://graph.facebook.com/?ids=' . urlencode($url);
  $link_body = wp_remote_retrieve_body(wp_remote_get($link));
  $json = json_decode($link_body);
  return $json->$url->comments;
}
```

`$link` returns something like `https://graph.facebook.com/?ids=http%3A%2F%2Fearmilk.com%2F2016%2F02%2F16%2Fget-ready-to-feel-nostalgic-as-stella-drops-the-slick-visuals-for-new-toy%2F`

Then, running `$link_body = wp_remote_retrieve_body(wp_remote_get($link));` on the live site, returns

``` json
{"error":{"message":"(#4) Application request limit 
reached","type":"OAuthException","is_transient":true,"code":4,"fbtrace_id":"EUNAVRNgnFu"}}`
```

I am not sure what app's limit yet, as the same thing doesn't happen on the clone site, but I think it's some Facebook OG API limit.

**Comment by andrebu** [comment]
Gonna try a batch request like so:

`https://graph.facebook.com/?ids=http%3A%2F%2Fearmilk.com%2F2016%2F02%2F16%2Fget-ready-to-feel-nostalgic-as-stella-drops-the-slick-visuals-for-new-toy%2F,http%3A%2F%2Fearmilk.com%2F2016%2F02%2F16%2Fsivik-delivers-time-after-time-with-new-single%2F`

**Comment by montreyw** [comment]
The only issue now is most every post has one google comment from our auto post.

**Comment by andrebu** [comment]
That's not an issue, is it?

And the facebook problem is now solved.   Still over API request limit.
<img width="959" alt="screen shot 2016-02-18 at 2 39 40 am" src="https://cloud.githubusercontent.com/assets/3777877/13136596/fa613d3e-d5e8-11e5-9fd0-04445594abbe.png">

`stdClass Object ( [error] => stdClass Object ( [message] => (#4) Application request limit reached [type] => OAuthException [is_transient] => 1 [code] => 4 [fbtrace_id] => AgE3COAZ+tj ) )`

**Comment by andrebu** [comment]
``` php
        <?php
            $url_batch = '';
            if (have_posts()) {
                while (have_posts()) {
                    the_post();
                    $one_url = get_permalink();
                    if (!$url_batch) {
                        $url_batch = urlencode($one_url);
                    } else {
                        $url_batch .= ',' . urlencode($one_url); 
                    }
                }
            }
            $batch_link = 'https://graph.facebook.com/?ids=' . $url_batch;
            //echo $batch_link;
            $batch_body = wp_remote_retrieve_body(wp_remote_get($batch_link));
            $batch_json_body = json_decode($batch_body);
            print_r ($batch_json_body);
            //return $json->$url->comments;
        ?>
```

**Comment by andrebu** [comment]
Found [this](http://stackoverflow.com/questions/29243606/facebook-graph-api-comment-count-suddenly-stopped-working), people having similar problems.  Apparently Facebook started limiting Open Graph API call requests very recently.

**Comment by andrebu** [comment]
https://developers.facebook.com/docs/facebook-login/access-tokens#apptokens

**Comment by montreyw** [comment]
Yeah it’s an issue because everyone post will say atleast 1 now which is
untrue. So then someone clicks into the post and see no comments.

Montrey Whittaker
Co-Founder / President

_earmilk.com http://earmilk.com/_
_twitter.com/earmilk http://twitter.com/earmilk_

_facebook.com/earmilk http://facebook.com/earmilk__instagram.com/earmilk_
http://instagram.com/earmilk

**Comment by andrebu** [comment]
So I'll just give the gplus count a 1 offset.

G+ will equal 0 when 0 or 1, 1 when 2, and 2 or more when 3 or more.

**Comment by andrebu** [comment]
On clone, a request to:

`https://graph.facebook.com/?ids=http%3A%2F%2Fallmilknoduds.com%2F2016%2F01%2F08%2Fanne-marie-shares-live-recording-of-new-single-gentleman-video%2F,http%3A%2F%2Fallmilknoduds.com%2F2016%2F01%2F08%2Fcomunite-presents-an-eclectic-lineup-for-their-tulum-beach-festival-next-week-audio-preview%2F,http%3A%2F%2Fallmilknoduds.com%2F2016%2F01%2F08%2Fthe-gentlemen-losers-share-gorgeous-new-lp%2F,http%3A%2F%2Fallmilknoduds.com%2F2016%2F01%2F08%2Fgovernors-ball-music-festival-announces-line-up%2F,http%3A%2F%2Fallmilknoduds.com%2F2016%2F01%2F08%2Ffritz-helder-gives-us-a-new-mantra-with-force-of-nature-premiere%2F,http%3A%2F%2Fallmilknoduds.com%2F2016%2F01%2F08%2Faxwell-ingrosso-preview-new-musical-direction-with-a-visualizer-video-for-dream-bigger%2F,http%3A%2F%2Fallmilknoduds.com%2F2016%2F01%2F08%2Fmick-jenkins-offers-fans-a-sip-in-the-form-of-grenade-theory-and-3000-advice%2F,http%3A%2F%2Fallmilknoduds.com%2F2016%2F01%2F08%2Fnef-the-pharaoh-and-cardo-connect-on-saydaat%2F,http%3A%2F%2Fallmilknoduds.com%2F2016%2F01%2F07%2Fsam-halabi-brings-aretha-franklins-deeper-love-into-2016-premiere%2F,http%3A%2F%2Fallmilknoduds.com%2F2016%2F01%2F07%2Ffriend-within-takes-on-neros-into-the-night-premiere%2F,http%3A%2F%2Fallmilknoduds.com%2F2016%2F01%2F07%2Fmat-zo-launches-the-producers-forum-shares-more-rejected-material-from-hinted-album%2F,http%3A%2F%2Fallmilknoduds.com%2F2016%2F01%2F07%2Fvalentino-khan-wiwek-deliver-explosive-jungle-terror-track-tropicana%2F`

===>

Returns this JSON object return:

```
stdClass Object
(
    [http://allmilknoduds.com/2016/01/08/anne-marie-shares-live-recording-of-new-single-gentleman-video/] => stdClass Object
        (
            [id] => http://allmilknoduds.com/2016/01/08/anne-marie-shares-live-recording-of-new-single-gentleman-video/
        )

    [http://allmilknoduds.com/2016/01/08/comunite-presents-an-eclectic-lineup-for-their-tulum-beach-festival-next-week-audio-preview/] => stdClass Object
        (
            [id] => http://allmilknoduds.com/2016/01/08/comunite-presents-an-eclectic-lineup-for-their-tulum-beach-festival-next-week-audio-preview/
        )

    [http://allmilknoduds.com/2016/01/08/the-gentlemen-losers-share-gorgeous-new-lp/] => stdClass Object
        (
            [id] => http://allmilknoduds.com/2016/01/08/the-gentlemen-losers-share-gorgeous-new-lp/
        )

    [http://allmilknoduds.com/2016/01/08/governors-ball-music-festival-announces-line-up/] => stdClass Object
        (
            [id] => http://allmilknoduds.com/2016/01/08/governors-ball-music-festival-announces-line-up/
        )

    [http://allmilknoduds.com/2016/01/08/fritz-helder-gives-us-a-new-mantra-with-force-of-nature-premiere/] => stdClass Object
        (
            [id] => http://allmilknoduds.com/2016/01/08/fritz-helder-gives-us-a-new-mantra-with-force-of-nature-premiere/
        )

    [http://allmilknoduds.com/2016/01/08/axwell-ingrosso-preview-new-musical-direction-with-a-visualizer-video-for-dream-bigger/] => stdClass Object
        (
            [id] => http://allmilknoduds.com/2016/01/08/axwell-ingrosso-preview-new-musical-direction-with-a-visualizer-video-for-dream-bigger/
            [comments] => 2
        )

    [http://allmilknoduds.com/2016/01/08/mick-jenkins-offers-fans-a-sip-in-the-form-of-grenade-theory-and-3000-advice/] => stdClass Object
        (
            [id] => http://allmilknoduds.com/2016/01/08/mick-jenkins-offers-fans-a-sip-in-the-form-of-grenade-theory-and-3000-advice/
        )

    [http://allmilknoduds.com/2016/01/08/nef-the-pharaoh-and-cardo-connect-on-saydaat/] => stdClass Object
        (
            [id] => http://allmilknoduds.com/2016/01/08/nef-the-pharaoh-and-cardo-connect-on-saydaat/
        )

    [http://allmilknoduds.com/2016/01/07/sam-halabi-brings-aretha-franklins-deeper-love-into-2016-premiere/] => stdClass Object
        (
            [id] => http://allmilknoduds.com/2016/01/07/sam-halabi-brings-aretha-franklins-deeper-love-into-2016-premiere/
        )

    [http://allmilknoduds.com/2016/01/07/friend-within-takes-on-neros-into-the-night-premiere/] => stdClass Object
        (
            [id] => http://allmilknoduds.com/2016/01/07/friend-within-takes-on-neros-into-the-night-premiere/
        )

    [http://allmilknoduds.com/2016/01/07/mat-zo-launches-the-producers-forum-shares-more-rejected-material-from-hinted-album/] => stdClass Object
        (
            [id] => http://allmilknoduds.com/2016/01/07/mat-zo-launches-the-producers-forum-shares-more-rejected-material-from-hinted-album/
        )

    [http://allmilknoduds.com/2016/01/07/valentino-khan-wiwek-deliver-explosive-jungle-terror-track-tropicana/] => stdClass Object
        (
            [id] => http://allmilknoduds.com/2016/01/07/valentino-khan-wiwek-deliver-explosive-jungle-terror-track-tropicana/
        )

)
```

Going through the object:

``` php
<?php 
$post_url = get_permalink();
echo $facebook_batch_json->$post_url->comments;
?>
```

**Comment by andrebu** [comment]
After trying a batch call with the Access Token, facebook sent the data.   However, the call takes too long and significantly slows down page load.
